### ISSUE TITLE
Error: Firebase.set failed

### ISSUE THREAD

**Issue by ikemura23** [banbara23/yaeyama-hash-tag-backend#1]
run startしたら送信失敗した。
久々に動作させたので、全件送信されるはずなんだが...

```bash
$ npm run start

> yaeyama-hash-tag-backend@1.0.0 start /Users/k_ikemura/dev/yaeyama-hash-tag-backend
> node index.js

index start
scrape start
scrape send 鳩間島　 16 件
scrape send 石垣島　 17 件
scrape send 八重山　 19 件
scrape send 西表島　 18 件
scrape send 波照間島 15 件
scrape send 竹富町　 17 件
scrape send 黒島　　 19 件
scrape send 竹富島　 17 件
scrape send 小浜島　 18 件
scrape send 与那国島 16 件
scrape end
filter start
filter yaeyama      19 件
filter taketomicho  17 件
filter ishigaki     17 件
filter iriomote     18 件
filter taketomi     17 件
filter kohama       18 件
filter kuroshima    19 件
filter hatoma       16 件
filter hateruma     15 件
filter yonaguni     16 件
filter send /public_index
Error: Firebase.set failed: First argument contains undefined in property 'public.hatoma.11.caption'
    at Md (/Users/k_ikemura/dev/yaeyama-hash-tag-backend/node_modules/firebase/database-node.js:100:
67)
    at /Users/k_ikemura/dev/yaeyama-hash-tag-backend/node_modules/firebase/database-node.js:101:166
    at cb (/Users/k_ikemura/dev/yaeyama-hash-tag-backend/node_modules/firebase/database-node.js:46:3
56)
    at Md (/Users/k_ikemura/dev/yaeyama-hash-tag-backend/node_modules/firebase/database-node.js:100:
424)
    at /Users/k_ikemura/dev/yaeyama-hash-tag-backend/node_modules/firebase/database-node.js:101:166
    at cb (/Users/k_ikemura/dev/yaeyama-hash-tag-backend/node_modules/firebase/database-node.js:46:3
56)
    at Md (/Users/k_ikemura/dev/yaeyama-hash-tag-backend/node_modules/firebase/database-node.js:100:
424)
    at /Users/k_ikemura/dev/yaeyama-hash-tag-backend/node_modules/firebase/database-node.js:101:166
    at cb (/Users/k_ikemura/dev/yaeyama-hash-tag-backend/node_modules/firebase/database-node.js:46:3
56)
    at Md (/Users/k_ikemura/dev/yaeyama-hash-tag-backend/node_modules/firebase/database-node.js:100:
424)
    at Ld (/Users/k_ikemura/dev/yaeyama-hash-tag-backend/node_modules/firebase/database-node.js:99:6
94)
    at U.h.set (/Users/k_ikemura/dev/yaeyama-hash-tag-backend/node_modules/firebase/database-node.js
:248:241)
    at sendToFirebase (/Users/k_ikemura/dev/yaeyama-hash-tag-backend/src/filter.js:158:6)
    at Promise.resolve.then.then.then.then.then (/Users/k_ikemura/dev/yaeyama-hash-tag-backend/src/f
ilter.js:18:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
filter end
top start
top send /top
top end
index end
```

**Comment by ikemura23** [comment]
直後にリトライすると成功した。

```bash
$ npm run start

> yaeyama-hash-tag-backend@1.0.0 start /Users/k_ikemura/dev/yaeyama-hash-tag-backend
> node index.js

index start
scrape start
scrape send 波照間島 15 件
scrape send 鳩間島　 16 件
scrape send 竹富島　 17 件
scrape send 黒島　　 19 件
scrape send 小浜島　 19 件
scrape send 西表島　 17 件
scrape send 竹富町　 17 件
scrape send 石垣島　 17 件
scrape send 八重山　 19 件
scrape send 与那国島 16 件
scrape end
filter start
filter yaeyama      1 件
filter taketomicho  0 件
filter ishigaki     8 件
filter iriomote     1 件
filter taketomi     4 件
filter kohama       2 件
filter kuroshima    0 件
filter hatoma       0 件
filter hateruma     0 件
filter yonaguni     0 件
filter send /public_index
filter send /public
filter end
top start
top send /top
top end
index end
```
この結果はおかしい。
期待値は再度全件登録されるかと思ったが、さっきの失敗した分からの差分？の件数になっている。

**Comment by ikemura23** [comment]
原因

scrapeした鳩間のcaptionが**undefine**になっていた。
[ページ](https://www.instagram.com/p/BWI3aGIHRHS/)見ると確かにcaptionが無かった、こんな投稿できるなんて知らんわい。

```
{ code: 'BWI3aGIHRHS',
       caption: undefined,
       data: '2017年7月5日 05:45',
       thumbnail_src: 'https://scontent-nrt1-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/19623482_1859059224412064_3884854939217821696_n.jpg',
       display_src: 'https://scontent-nrt1-1.cdninstagram.com/t51.2885-15/e35/19623482_1859059224412064_3884854939217821696_n.jpg',
       is_video: false },
```

**Comment by ikemura23** [comment]
修正コミット
https://github.com/banbara23/yaeyama-hash-tag-backend/commit/dd464aabf24f517fe15080b17184a961705e4bb7
